# This is a basic workflow to help you get started with Actions

name: Testing Workflows

on:
  label:
    types: 
    - created
  issues:  
    types:
    - opened
jobs:
  print:
        run: 
          echo "Trigger - ${{ github.event_name }}, user - ${{ github.actor}}
